version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: dotnet restore
build:
  parallel: true
  verbosity: minimal
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
artifacts:
- path: '**\*.nupkg'
  name: 'PfxToSnk'
deploy:
- provider: GitHub
  force_update: true
  tag: $(appveyor_repo_tag_name)
  release: v$(appveyor_build_version)
  auth_token:
    secure: 0RltkfAMN35pApf7xYqjwy1EgsVeniSYPv35Qb9ntHY1b4SC51QYLXVVfklvw09j
  artifact: /.*\.nupkg/            # upload all NuGet packages to release assets
  draft: false
  prerelease: false
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only  
- provider: NuGet
  api_key:
    secure: Q/HUObjarHxWF0NlnHBDY5uMQHM4ESyKfFCYdbRVfsNrWUFozADu6FMvh44gEmFk
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only  
  
