version: 0.0.0
image: Visual Studio 2017
configuration: Release
platform: Any CPU

install: 
  - ps: $env:package_version = (Get-Content -Raw -Path package.json | ConvertFrom-Json).version 
  - ps: Update-AppveyorBuild -Version "$env:package_version"
#  - ps: Update-AppveyorBuild -Version "$env:package_version-$env:APPVEYOR_BUILD_NUMBER"

before_build:
- cmd: dotnet restore

build:
  parallel: true
  verbosity: minimal

dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_file_version: '$(appveyor_build_version)'

artifacts:
- path: '**\*.nupkg'
  name: 'PfxToSnk'

deploy:
  provider: NuGet
  api_key:
    secure: 4ecLISsp0ABX9R23S/IMP0HP7bMftyHBZBDU0LEvhgJP/lhTTUvmOl1SSZNM6U/4
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master                 # release from master branch only
    appveyor_repo_tag: true        # deploy on tag push only      
  
