version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
before_build:
- cmd: dotnet restore
build:
  parallel: true
  verbosity: minimal
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: $(appveyor_build_version)
artifacts:
- path: '**\*.nupkg'
  name: 'PfxToSnk'
deploy:
  provider: NuGet
  api_key:
    secure: 4ecLISsp0ABX9R23S/IMP0HP7bMftyHBZBDU0LEvhgJP/lhTTUvmOl1SSZNM6U/4
  skip_symbols: false
  artifact: /.*\.nupkg/
  on:
    branch: master                 # release from master branch only
  
